export { default as Urban } from "@/components/svgs/urban.svg";
export { default as Sales } from "@/components/svgs/sales.svg";
export { default as Survey } from "@/components/svgs/Survey.svg";
export { default as Piggery } from "@/components/svgs/Piggery.svg";
export { default as Developer } from "@/components/svgs/Developer.svg";
export { default as Construct } from "@/components/svgs/Construct.svg";
export { default as Borehole } from "@/components/svgs/Borehole.svg";
export { default as Estate } from "@/components/svgs/Estate.svg";
export { default as Drawing } from "@/components/svgs/Drawings.svg";
export { default as Bar } from "@/components/svgs/Bar.svg";
// export { default as Whatsapp } from "@/components/svgs/Whatsapp.svg";
export { default as Instagram } from "./Instagram.svg";
export { default as Pinterest } from "./Pinterest.svg";
export { default as Youtube } from "./Youtube.svg";
export { default as Whatsapp } from "./Whatsapp.svg";
export { default as Ticktok } from "./Ticktok.svg";
// export { default as Caret } from "./Caret.svg";
export { default as Facebook } from "./Facebook.svg";
export { default as Twitter } from "./Twitter.svg";
export { default as Mail } from "./Mail.svg";
export { default as Google } from "./google.svg";
export { default as Safety } from "./Safety.svg";
export { default as Workforce } from "./Workforce.svg";
export { default as Experience } from "./Experience.svg";
export { default as Optimize } from "./Optimize.svg";
export { default as Relationship } from "./Relationship.svg";
export { default as Value } from "./value.svg";
